# relative weighting (diagonal matrices) for the cost funcion
# based on more or less physical considerations

torque: [[0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0], # sliding joint
          # first arm
         [0,   1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
         [0,   0,   1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0], 
         [0,   0,   0, 2.2,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0], 
         [0,   0,   0,   0, 2.2,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0], 
         [0,   0,   0,   0,   0, 6.6,   0,   0,   0,   0,   0,   0,   0,   0,   0], 
         [0,   0,   0,   0,   0,   0, 6.6,   0,   0,   0,   0,   0,   0,   0,   0], 
         [0,   0,   0,   0,   0,   0,   0, 6.6,   0,   0,   0,   0,   0,   0,   0],
         # second arm
         [0,   0,   0,   0,   0,   0,   0,   0,   1,   0,   0,   0,   0,   0,   0],
         [0,   0,   0,   0,   0,   0,   0,   0,   0,   1,   0,   0,   0,   0,   0], 
         [0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 2.2,   0,   0,   0,   0], 
         [0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 2.2,   0,   0,   0], 
         [0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 6.6,   0,   0], 
         [0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 6.6,   0], 
         [0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 6.6]] 

vel: [[0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0], # sliding joint
      # first arm
      [0, 3.2,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
      [0,   0, 3.2,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0], 
      [0,   0,   0, 2.0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
      [0,   0,   0,   0, 2.0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0], 
      [0,   0,   0,   0,   0, 1.0,   0,   0,   0,   0,   0,   0,   0,   0,   0], 
      [0,   0,   0,   0,   0,   0, 1.0,   0,   0,   0,   0,   0,   0,   0,   0], 
      [0,   0,   0,   0,   0,   0,   0, 1.0,   0,   0,   0,   0,   0,   0,   0],
      # second arm
      [0,   0,   0,   0,   0,   0,   0,   0, 3.2,   0,   0,   0,   0,   0,   0],
      [0,   0,   0,   0,   0,   0,   0,   0,   0, 3.2,   0,   0,   0,   0,   0], 
      [0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 2.0,   0,   0,   0,   0],
      [0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 2.0,   0,   0,   0], 
      [0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 1.0,   0,   0], 
      [0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 1.0,   0], 
      [0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 1.0]] 

cl_man: 

      rot: 1.0

      trasl: 1.0
        