link1_coll:

  coll_radii: 0.07

link2_coll:

  coll_radii: 0.053

link3_coll:

  coll_radii: 0.08

link4_coll:

  coll_radii: 0.08

link5_coll: 

  coll_radii: 0.08

link6_coll:

  coll_radii: 0.07

link7_coll: 

  coll_radii: 0.05
